---
# Dynamic execution playbook for influxdb
- name: Execute verify for influxdb Service
  hosts: monitor11
  become: true
  vars:
    verify_timestamp: "{{ ansible_date_time.iso8601 }}"
    report_root: "/home/lavender/sandbox/ansible/jackaltx/solti-monitoring/verify_output"
    project_root: "/home/lavender/sandbox/ansible/jackaltx/solti-monitoring"
    all_verify_results: {}
    all_verify_failed: {}
  pre_tasks:
    - name: Ensure verify output directory exists
      ansible.builtin.file:
        path: "{{ report_root }}/{{ ansible_distribution | lower }}"
        state: directory
        mode: "0755"
      delegate_to: localhost
      become: false
  tasks:
    - name: Include role tasks
      ansible.builtin.include_role:
        name: influxdb
        tasks_from: verify
