---
# defaults file for telegraf

# can be absent or present
telegraf_state: present

telegraf_config: /etc/telegraf/telegraf.conf
telegraf_default_env: /etc/default/telegraf

# a list of metrics to pick from
influxdb_apache: false
influxdb_mariadb: false
influxdb_memcache: false
influxdb_redis: false

# used for absent
telegraf_delete_config: false
telegraf_delete_data: false

# use to clean out config data
telegraf_clean_inputs: false

# a list of dashboards
telegraf_outputs: [localhost]

# a list of places to ping
telegraf_ping_loc:
  - 1.1.1.1
  - 8.8.8.8
  - www.google.com

# by default we are in in testing mode  TODAY!!!
telegraf_testing: true

# these are for influxd outputs
telgraf2influxdb_configs: {}

# used for static testing.  TODO go better idea!
telegraf_localhost_token: "ChangeThisToYourInfluxbdToken"

# mariadb/mysql monitoring capability
telegraf_mysql_auth: "{{ lookup('env', 'MYSQL_AUTH') }}"
