---
collections:
  - name: community.general
  - name: community.proxmox
  - name: containers.podman
  - name: ansible.posix
  - name: jackal.solti_platforms # for molecule testing only ???  CLAUDE confirm this
