---
- name: Converge
  hosts: all
  become: true
  serial: "{{ lookup('env', 'MOLECULE_SERIAL', default='0') }}"

  tasks:
    - name: Set test run timestamp (used across converge and verify)
      set_fact:
        verify_timestamp: "{{ ansible_facts['date_time']['iso8601'] }}"
        cacheable: yes

    - name: Debug information
      debug:
        msg:
          - "Playbook dir: {{ playbook_dir }}"
          - "Roles path: {{ playbook_dir }}/../../roles"
          - "Project_root: {{ project_root }}"
          - "Distribution: {{ ansible_facts['distribution'] }}"
          - "Testing capability: {{ testing_capabilities }}"
          - "Test timestamp: {{ verify_timestamp }}"

    - name: Load capability role definitions
      include_vars:
        file: "{{ project_root }}/molecule/vars/capabilities.yml"

    - debug:
        var: monitoring_capabilities
        verbosity: 1

    - name: Validate testing capabilities
      assert:
        that:
          - capability in monitoring_capabilities.keys()
        fail_msg: "Invalid capability specified: {{ capability }}"
        success_msg: "Valid capability: {{ capability }}"
      loop: "{{ testing_capabilities }}"
      loop_control:
        loop_var: capability

    - name: Get roles for selected capabilities
      set_fact:
        roles_to_include: >-
          {{
            testing_capabilities |
            map('extract', monitoring_capabilities) |
            map(attribute='roles') |
            flatten |
            list
          }}

    - name: Debug role inclusion
      debug:
        msg:
          - "Testing Capabilities: {{ testing_capabilities }}"
          - "Roles to Include: {{ roles_to_include }}"
        verbosity: 0

    - name: Include roles to be tested
      include_role:
        name: "{{ project_root }}/roles/{{ role_name }}"
      loop: "{{ roles_to_include }}"
      loop_control:
        loop_var: role_name
        label: "Including role: {{ role_name }}"
