---
# Create VM by cloning latest template using solti-platforms tasks
# This replaces direct API calls with SSH-based qm commands via solti-platforms role
- name: Create VM using solti-platforms
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    # Map template names to distribution identifiers
    distribution_map:
      "rocky9-template": "rocky9"
      "debian-12-template": "debian12"

    # Derive distribution from PROXMOX_TEMPLATE env var
    template_distribution: "{{ distribution_map[proxmox_template] | default('debian12') }}"

    # Proxmox host configuration
    proxmox_host: "{{ lookup('env', 'PROXMOX_NODE') | default('magic', true) }}"

  tasks:
    - name: Debug molecule configuration
      ansible.builtin.debug:
        msg:
          - "Proxmox Host: {{ proxmox_host }}"
          - "Template Distribution: {{ template_distribution }}"
          - "Target VMID: {{ proxmox_vmid }}"
          - "VM Name: {{ proxmox_vm_name }}"
          - "VM IP: {{ molecule_ip }}"
        verbosity: 1

    - name: Clone and configure VM via SSH on Proxmox host
      ansible.builtin.include_role:
        name: jackaltx.solti_platforms.proxmox_template
        tasks_from: clone_latest_template
      vars:
        ansible_host: "{{ proxmox_host }}"
        ansible_connection: ssh
        ansible_user: root
        clone_vmid: "{{ proxmox_vmid }}"
        clone_name: "{{ proxmox_vm_name }}"
        clone_ip: "{{ molecule_ip }}"
        clone_gateway: "192.168.101.254"
        clone_netmask: 24
        clone_disk_size: "20G"
        clone_full: 0  # Linked clone for fast molecule testing
      delegate_to: "{{ proxmox_host }}"

    - name: Display VM creation summary
      ansible.builtin.debug:
        msg:
          - "=== VM Created Successfully ==="
          - "VMID: {{ proxmox_vmid }}"
          - "Name: {{ proxmox_vm_name }}"
          - "IP: {{ molecule_ip }}"
          - "Distribution: {{ template_distribution }}"
