---
#
#
# ========================================================================

- name: Prepare VM
  hosts: localhost

  tasks:
    # ................................................................
    # note this has to be loaded in each phase playbook!
    #
    - name: Load shared test configuration
      ansible.builtin.include_vars:
        file: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') }}/molecule/shared/vars/test-config.yml"
      delegate_to: localhost
      run_once: true

    - name: Start the VM
      community.general.proxmox_kvm:
        api_host: "{{ lookup('env', 'PROXMOX_URL') }}"
        api_user: "{{ lookup('env', 'PROXMOX_USER') }}"
        api_token_id: "{{ lookup('env', 'PROXMOX_TOKEN_ID') }}"
        api_token_secret: "{{ lookup('env', 'PROXMOX_TOKEN_SECRET') }}"
        node: "{{ lookup('env', 'PROXMOX_NODE') }}"
        vmid: "{{ proxmox_vmid }}"
        state: started
        timeout: 300

    - name: Wait for VM to boot
      pause:
        seconds: 30

    - name: Wait for SSH
      wait_for:
        host: "{{ molecule_ip }}"
        port: 22
        timeout: 300

    - name: Display connection status
      debug:
        msg: "VM id: {{ proxmox_vmid }} named: {{ proxmox_vm_name }} at ip {{ molecule_ip }} is ready"

#
#
# ========================================================================
# The pkg installs could have been done when I created the VMS,
#   but I wanted an way to dynamically add packages
#
- name: Install prerequisites
  hosts: all # This is all the VMs that were created (we are currently serial)
  become: true
  tasks:
    - name: Wait for cloud-init to finish
      command: cloud-init status --wait
      register: cloud_init_status
      changed_when: false
      failed_when: false

    - name: Branch on Debian
      when: ansible_facts['distribution'] == "Debian"
      block:
        - name: Install required packages
          apt:
            name:
              - gpg
              - ca-certificates
              - qemu-guest-agent
              - lsof
            update_cache: yes
            state: present

        - name: Ensure qemu-guest-agent is running
          systemd:
            name: qemu-guest-agent
            state: started
            enabled: true

    - name: Branch on Rocky
      when: ansible_facts['distribution'] == "Rocky"
      block:
        - name: Install required packages
          dnf:
            name:
              - lsof
            update_cache: yes
            state: present

    - name: Fail for unsupported
      fail:
        msg: "Distribution {{ ansible_facts['distribution'] }} not supported"
      when: ansible_facts['distribution'] != "Debian" and ansible_facts['distribution'] != "Rocky"
