---
# Molecule dependency requirements for Proxmox scenario
# This file is referenced in molecule.yml dependency section

collections:
  # solti-platforms collection for template discovery and cloning
  # Installed via symlink at ~/.ansible/collections/ansible_collections/jackaltx/solti_platforms
  # For CI/CD environments, override with git source in a separate requirements-ci.yml
  - name: jackaltx.solti_platforms
