---
- name: Verify
  hosts: all
  become: true

  tasks:
    - name: Initialize verify results dictionaries
      set_fact:
        all_verify_results: {}
        all_verify_failed: {}

    - name: Set verify timestamp (if not already set from converge)
      set_fact:
        verify_timestamp: "{{ verify_timestamp | default(ansible_facts['date_time']['iso8601']) }}"

    - name: Load capability role definitions
      include_vars:
        file: "{{ project_root }}/molecule/vars/capabilities.yml"

    - name: Debug information
      debug:
        msg:
          - "Playbook dir: {{ playbook_dir }}"
          - "Roles path: {{ playbook_dir }}/../../roles"
          - "Project_root: {{ project_root }}"
          - "Distribution: {{ ansible_facts['distribution'] }}"
          - "Testing capability: {{ testing_capabilities }}"

    # .......................................................................
    - name: Run container diagnostics
      include_tasks:
        file: "../shared/diagnostics/main.yml"
      vars:
        report_suffix: "pre-verify"

    # .......................................................................
    - name: Run capability-specific verifications
      include_tasks: "../shared/verify/verify-{{ capability }}.yml"
      loop: "{{ testing_capabilities }}"
      loop_control:
        loop_var: capability
        label: "Verifying {{ capability }} capability"
