---
dependency:
  name: galaxy
  options:
    requirements-file: requirements.yml
    ignore-errors: true

driver:
  name: docker
  options:
    managed: true

platforms:
  # - name: "uut-ct0"
  #   image: "ghcr.io/jackaltx/testing-containers/debian12-ssh:latest"
  #   network: monitoring-net"
  #   command: "/sbin/init"
  #   privileged: true
  #   volumes:
  #     - /sys/fs/cgroup:/sys/fs/cgroup:rw
  #   cgroupns_mode: host
  #   ssh_host: "127.0.0.1"
  #   ssh_port: 2223
  #   ssh_user: "jackaltx"
  #   connection: ssh

  - name: "uut-ct1"
    image: "ghcr.io/jackaltx/testing-containers/rocky93-ssh:latest"
    network: monitoring-net
    command: "/sbin/init"
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    ssh_host: "127.0.0.1"
    ssh_port: 2222
    ssh_user: "jackaltx"
    connection: ssh

  - name: "uut-ct2"
    image: "ghcr.io/jackaltx/testing-containers/ubuntu24-ssh:latest"
    network: monitoring-net
    command: "/sbin/init"
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    ssh_host: "127.0.0.1"
    ssh_port: 2224
    ssh_user: "jackaltx"
    connection: ssh

provisioner:
  name: ansible
  env:
    ANSIBLE_FORCE_COLOR: "1"
  log: true
  config_options:
    defaults:
      interpreter_python: auto_silent
      host_key_checking: false
      remote_tmp: /tmp/ansible-tmp
      local_tmp: /tmp/ansible-tmp
  playbooks:
    prepare: prepare.yml
  inventory:
    group_vars:
      all:
        # ansible_user: ansible
        proxmox_vmid: 9100
        project_root: ${MOLECULE_PROJECT_DIRECTORY}
        report_root: ${MOLECULE_PROJECT_DIRECTORY}/verify_output

        telgraf2influxdb_configs:
          localhost:
            url: "http://127.0.0.1"
            token: ""
            bucket: "telegraf"
            org: "lavnet"
            namedrop: '["influxdb_oss"]'
            bucket_tag: ""
            exclude_bucket_tag: ""
            ping_timeout: "0s"
            read_idle_timeout: "0s"
            insecure_skip_verify: false
        loki_local_storage: true
        influxdb_test: true
        influxdb_configure: true
        alloy_loki_endpoint: "127.0.0.1"

    host_vars:
      debian-instance:
        ansible_connection: docker
        ansible_user: root

      rocky-instance:
        ansible_connection: docker
        ansible_user: root

scenario:
  name: github
  test_sequence:
    - dependency
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - verify
    - cleanup
    - destroy

verifier:
  name: ansible
