---
# Tasks for installing Wazuh agent

# Install common prerequisites
- name: Install common prerequisites
  package:
    name: "{{ common_packages }}"
    state: present
  when: not ansible_check_mode

# Set up repository - Debian-based
- name: Add Wazuh repository key
  apt_key:
    url: "{{ wazuh_repo_key_url }}"
    state: present
  when: ansible_os_family == "Debian" and not ansible_check_mode

- name: Add Wazuh repository
  apt_repository:
    repo: "{{ wazuh_repo_url }}"
    state: present
    update_cache: yes
  when: ansible_os_family == "Debian" and not ansible_check_mode

# Set up repository - RHEL-based
- name: Add Wazuh repository
  yum_repository:
    name: wazuh
    description: Wazuh repository
    baseurl: "{{ wazuh_repo_url }}"
    gpgcheck: yes
    gpgkey: "{{ wazuh_repo_key_url }}"
    enabled: yes
  when: ansible_os_family == "RedHat" and not ansible_check_mode

# Install Wazuh agent package
- name: Install Wazuh agent
  package:
    name: "{{ wazuh_packages }}"
    state: present
  when: not ansible_check_mode
  register: package_installed

# Basic initial configuration
- name: Configure agent to connect to Wazuh server
  command: >
    /var/ossec/bin/agent-auth -m {{ wazuh_server_address }}
    -p {{ wazuh_server_port | default(1515) }}
    {% if wazuh_agent_group is defined and wazuh_agent_group | length > 0 %}
    -G {{ wazuh_agent_group }}
    {% endif %}
    {% if wazuh_registration_password is defined and wazuh_registration_password | length > 0 %}
    -P {{ wazuh_registration_password }}
    {% endif %}
  args:
    creates: /var/ossec/etc/client.keys
  when: not ansible_check_mode and (package_installed is changed or package_installed is success)
  register: agent_registered
  ignore_errors: true

# Ensure service is enabled and started
- name: Enable and start Wazuh agent service
  service:
    name: "{{ wazuh_service_name }}"
    enabled: yes
    state: started
  # when: not ansible_check_mode and (agent_registered is success or agent_registered is skipped)
  when: >
    not ansible_check_mode and
    (agent_registered is defined and (agent_registered is success or agent_registered is skipped))
