---
# Remove Wazuh agent

# Stop and disable service
- name: Stop and disable Wazuh agent service
  service:
    name: "{{ wazuh_service_name }}"
    state: stopped
    enabled: no
  failed_when: false
  when: not ansible_check_mode

# Remove package - Debian
- name: Remove Wazuh agent package (Debian)
  apt:
    name: "{{ wazuh_agent_package }}"
    state: absent
    purge: yes
  when: ansible_os_family == "Debian" and not ansible_check_mode

# Remove package - RedHat
- name: Remove Wazuh agent package (RedHat)
  yum:
    name: "{{ wazuh_agent_package }}"
    state: absent
  when: ansible_os_family == "RedHat" and not ansible_check_mode

# Remove repository - Debian
- name: Remove Wazuh repository (Debian)
  apt_repository:
    repo: "{{ wazuh_repo_url }}"
    state: absent
    update_cache: yes
  when: ansible_os_family == "Debian" and not ansible_check_mode

# Remove repository - RedHat
- name: Remove Wazuh repository (RedHat)
  yum_repository:
    name: wazuh
    state: absent
  when: ansible_os_family == "RedHat" and not ansible_check_mode

# ..........................................................................
# Add to tasks/remove.yml before removing packages
- name: Backup ossec.conf before removal
  copy:
    src: "{{ wazuh_config_file }}"
    dest: "{{ wazuh_config_file }}.bak-{{ ansible_date_time.iso8601 | regex_replace(':', '-') }}"
    remote_src: yes
  when: not ansible_check_mode
  ignore_errors: true

# ..........................................................................
# Clean up configuration
- name: Remove Wazuh configuration directory
  file:
    path: "{{ wazuh_config_dir }}"
    state: absent
  when: not ansible_check_mode
