---
# Verify Wazuh agent installation and configuration

# Check if package is installed
- name: Check if Wazuh agent package is installed
  package_facts:
    manager: auto
  when: not ansible_check_mode

- name: Verify Wazuh agent package installation
  debug:
    msg: "Wazuh agent is installed: {{ wazuh_agent_package in ansible_facts.packages }}"
  when: not ansible_check_mode

# Check if service is running
- name: Check if Wazuh agent service is running
  service_facts:
  when: not ansible_check_mode

- name: Verify Wazuh agent service status
  debug:
    msg: "Wazuh agent service is running: {{ ansible_facts.services[wazuh_service_name].state == 'running' }}"
  when: not ansible_check_mode and wazuh_service_name in ansible_facts.services

# Check connection to server
- name: Check connection to Wazuh server
  shell: /var/ossec/bin/agent_control -i {{ ansible_facts.hostname }} -s
  register: connection_status
  changed_when: false
  failed_when: false
  when: not ansible_check_mode

- name: Verify connection to Wazuh server
  debug:
    msg: "{{ connection_status.stdout }}"
  when: not ansible_check_mode and connection_status is defined

# Check configuration validity
- name: Verify Wazuh agent configuration
  command: /var/ossec/bin/agent-control -t
  register: verify_result
  changed_when: false
  failed_when: verify_result.rc != 0
  when: not ansible_check_mode

- name: Display configuration verification result
  debug:
    msg: "Configuration verification: {{ 'Passed' if verify_result.rc == 0 else 'Failed' }}"
  when: not ansible_check_mode and verify_result is defined
##############################
