---
# Used by the molecule integration convergence and verification
#
#  I envision this data being assembled from the parts
#  instead of this "top down build"
#
#  This is used by both the Podman CT and Proxmox VM molecule testing
#  for Debian and RHEL distros.
#
#  I can see this being used to for different subsets, but
#  currently the configuraiton variables used for convergence
#  are defined in the molecule.yml.
#
#  This mechanism allows a single script to test interactions.
#  Which for this is  send and recieve logs/metrics.
#
#  verify_role is a list of tasks which basically dispacthed call into the role
#  itself, this allows a task access to all the variables.  The purpose is to
#  test the service working.
#
#  verify_tasks is a list tasks that address interacts betwen the sender/reciever.
#
#  Note: we are inbetween times for Influxdb. V3 is radically different
#  from V2.  No built in gui. allows S3 buckets. Python based plugins for alerting.
#
#  So for now, I will test both versions influxd.
#
# ..............................................................
# Version 2
monitoring_capabilities:
  logs:
    roles:
      - loki
      - alloy
    required_packages:
      Debian: &debian_logs_deps
        - gpg
        - ca-certificates
        - lsof
      Ubuntu: *debian_logs_deps # Reuse Debian dependencies
      RedHat: &redhat_logs_deps
        - gpg
        - ca-certificates
        - lsof
        - procps-ng
      Rocky: *redhat_logs_deps # Reuse RedHat dependencies
    verify_role_tasks:
      loki:
        - verify.yml
        - verify1.yml
      alloy:
        - verify.yml
    verify_tasks:
      - verify-logs.yml
    service_names:
      - loki
      - alloy
    service_ports:
      - 3100
      - 12345

  metrics:
    roles:
      - influxdb
      - influxdb3
      - telegraf
    required_packages:
      Debian: &debian_metrics_deps
        - gpg
        - ca-certificates
        - lsof
      Ubuntu: *debian_metrics_deps
      RedHat: &redhat_metrics_deps
        - gpg
        - ca-certificates
        - lsof
        - procps-ng
      Rocky: *redhat_metrics_deps
    verify_role_tasks:
      influxdb:
        - verify.yml
      influxdb3:
        - verify.yml
        - verify-collecting.yml
    verify_tasks:
      - verify-metrics.yml
      - verify-metrics-v3.yml
    service_names:
      - influxdb
      - influxdb3-core
      - telegraf
    service_ports:
      - 8086
      - 8181
