---
# Debian/Ubuntu specific variables
wazuh_agent_package: wazuh-agent
wazuh_repo_key_url: "https://packages.wazuh.com/key/GPG-KEY-WAZUH"
wazuh_repo_url: "deb https://packages.wazuh.com/4.x/apt/ stable main"
wazuh_config_dir: /var/ossec/etc
wazuh_config_file: "{{ wazuh_config_dir }}/ossec.conf"
wazuh_packages:
  - apt-transport-https
  - wazuh-agent

# Default log locations for Debian-based systems
log_locations:
  dpkg: "/var/log/dpkg.log"
  apache_access: "/var/log/apache2/access.log"
  apache_error: "/var/log/apache2/error.log"
  nginx_access: "/var/log/nginx/access.log"
  nginx_error: "/var/log/nginx/error.log"
  mysql: "/var/log/mysql/error.log"
  postgresql: "/var/log/postgresql/postgresql*.log"
  auth: "/var/log/auth.log"
  syslog: "/var/log/syslog"

# Service detection commands
service_detection:
  apache: "systemctl list-units --type=service | grep -E 'apache2|httpd'"
  nginx: "systemctl list-units --type=service | grep nginx"
  mysql: "systemctl list-units --type=service | grep mysql"
  postgresql: "systemctl list-units --type=service | grep postgresql"
  podman: "which podman"
  docker: "which docker"
