---
# Deployment profiles for different environments

# This was the original...I am keeping it around for debug phase.

# .............................................................................................
# Profile: isolated
# For isolated LANs where another tool is the primary log collector
# Focus on Wazuh's security monitoring capabilities with minimal log collection
# .............................................................................................

isolated_profile:
  wazuh_security_modules:
    rootcheck:
      enabled: yes
      frequency: 43200 # 12 hours
    syscheck:
      enabled: yes
      frequency: 43200 # 12 hours
    sca:
      enabled: yes
      interval: "12h"
    syscollector:
      enabled: yes
      interval: "1h"
    cis_cat:
      enabled: no # Resource-intensive, disabled
    osquery:
      enabled: no # Resource-intensive, disabled
    active_response:
      enabled: no # Often not needed in isolated environments

  wazuh_log_monitoring:
    system:
      journald: no # No journald monitoring
      audit: yes # Security-relevant
      dpkg: no # Not security-critical
      rpm: no # Not security-critical

    web:
      # No web server log monitoring - handled by other collector
      apache_access: no
      apache_error: no
      nginx_access: no
      nginx_error: no

    database:
      # No database log monitoring - handled by other collector
      mysql: no
      postgresql: no

    commands:
      # Keep basic system commands for security awareness
      disk_space: yes # Useful for security (full disks can cause issues)
      network_ports: yes # Security-relevant
      last_logins: yes # Security-relevant
      open_files: no
      process_list: no

    journald_filters: [] # No journald filters since journald is disabled

    custom: [] # Custom log monitoring typically not needed

# .............................................................................................
# Profile: internal
# For internal services where Wazuh complements other tools
# Focus on security monitoring plus only critical logs
# .............................................................................................

internal_profile:
  wazuh_security_modules:
    rootcheck:
      enabled: yes
      frequency: 21600 # Every 6 hours - more frequent than isolated
    syscheck:
      enabled: yes
      frequency: 21600 # Every 6 hours - more frequent than isolated
    sca:
      enabled: yes
      interval: "6h" # More frequent assessment
    syscollector:
      enabled: yes
      interval: "1h"
    cis_cat:
      enabled: no # Still resource-intensive
    osquery:
      enabled: no # Still resource-intensive
    active_response:
      enabled: yes # Enable automatic responses

  wazuh_log_monitoring:
    system:
      journald: yes # Enabled but filtered (see journald_filters)
      audit: yes # Security-relevant
      dpkg: yes # Track package changes on internal systems
      rpm: yes # Track package changes on internal systems

    web:
      # Only critical errors, not access logs
      apache_access: no
      apache_error: yes
      nginx_access: no
      nginx_error: yes

    database:
      # Only critical errors
      mysql: yes
      postgresql: yes

    commands:
      # All system commands for better monitoring
      disk_space: yes
      network_ports: yes
      last_logins: yes
      open_files: no
      process_list: no

    # Filter journald to only include critical and error messages
    journald_filters:
      - name: critical_errors
        enabled: yes
        query: "PRIORITY<=3" # Emergency, Alert, Critical only

      - name: authentication
        enabled: yes
        query: "SYSLOG_IDENTIFIER=sudo OR SYSLOG_IDENTIFIER=su"

      - name: systemd_failures
        enabled: yes
        query: "UNIT=systemd.service AND PRIORITY<=4" # Include errors

    custom: [] # Define custom logs as needed

# .............................................................................................
# Profile: internet_facing
# For internet-connected systems where Wazuh is the primary security tool and log collector
# .............................................................................................

internet_facing_profile:
  wazuh_security_modules:
    rootcheck:
      enabled: yes
      frequency: 7200 # Every 2 hours - very frequent
    syscheck:
      enabled: yes
      frequency: 7200 # Every 2 hours - very frequent
    sca:
      enabled: yes
      interval: "3h" # Very frequent assessment
    syscollector:
      enabled: yes
      interval: "30m" # More frequent inventory collection
    cis_cat:
      enabled: yes # Enable compliance scanning
      interval: "1d" # Daily scanning
    osquery:
      enabled: yes # Enable advanced endpoint visibility
    active_response:
      enabled: yes # Enable automatic responses
      block_malicious: yes # Block malicious activity

  wazuh_log_monitoring:
    system:
      journald: yes # Full journald monitoring
      audit: yes # Complete audit trail
      dpkg: yes # Track all package changes
      rpm: yes # Track all package changes

    web:
      # Full web server logging
      apache_access: yes
      apache_error: yes
      nginx_access: yes
      nginx_error: yes

    database:
      # Full database logging
      mysql: yes
      postgresql: yes

    commands:
      # All system commands plus additional security checks
      disk_space: yes
      network_ports: yes
      last_logins: yes
      open_files: yes
      process_list: yes

    # Comprehensive journald monitoring with service-specific filters
    journald_filters:
      - name: all_errors
        enabled: yes
        query: "PRIORITY<=4" # Emergency through Error

      - name: web_all
        enabled: yes
        query: "UNIT=apache2.service OR UNIT=httpd.service OR UNIT=nginx.service"

      - name: ssh_all
        enabled: yes
        query: "UNIT=sshd.service"

      - name: authentication
        enabled: yes
        query: "SYSLOG_IDENTIFIER=sudo OR SYSLOG_IDENTIFIER=su"

    # Define custom application logs based on deployment
    custom:
      - path: /var/log/auth.log
        format: syslog
        enabled: yes

      - path: /var/log/secure
        format: syslog
        enabled: yes
##############################
