---
# Deployment profiles for different environments

# .............................................................................................
# Profile: isolated
# For isolated LANs where another tool is the primary log collector
# Focus on Wazuh's security monitoring capabilities with minimal log collection
# .............................................................................................

isolated_profile:
  wazuh_security_modules:
    rootcheck:
      enabled: yes
      frequency: 43200 # 12 hours
    syscheck:
      enabled: yes
      frequency: 43200 # 12 hours
    sca:
      enabled: yes
      interval: "12h"
    syscollector:
      enabled: yes
      interval: "1h"
    cis_cat:
      enabled: no # Resource-intensive, disabled
    osquery:
      enabled: no # Resource-intensive, disabled
    active_response:
      enabled: no # Often not needed in isolated environments SMELL?

  wazuh_log_monitoring:
    system:
      journald: no # No journald monitoring
      audit: yes # Security-relevant
      dpkg: no # Not security-critical
      rpm: no # Not security-critical

    commands:
      # Keep basic system commands for security awareness
      disk_space: no # Useful for security (full disks can cause issues)
      network_ports: no # Security-relevant
      last_logins: no # Security-relevant
      open_files: no
      process_list: no

    journald_filters: [] # No journald filters since journald is disabled

    custom: [] # Custom log monitoring typically not needed

# .............................................................................................
# Profile: internal
# For internal services where Wazuh complements other tools
# Focus on security monitoring plus only critical logs
# .............................................................................................

internal_profile:
  wazuh_security_modules:
    rootcheck:
      enabled: yes
      frequency: 21600 # Every 6 hours - more frequent than isolated
    syscheck:
      enabled: yes
      frequency: 21600 # Every 6 hours - more frequent than isolated
    sca:
      enabled: yes
      interval: "6h" # More frequent assessment
    syscollector:
      enabled: yes
      interval: "1h"
    cis_cat:
      enabled: no # Still resource-intensive
    osquery:
      enabled: no # Still resource-intensive
    active_response:
      enabled: no # disable automatic responses

  wazuh_log_monitoring:
    system:
      journald: yes # Enabled but filtered (see journald_filters)
      audit: yes # Security-relevant
      dpkg: yes # Track package changes on internal systems
      rpm: yes # Track package changes on internal systems

    commands:
      # All system commands for better monitoring
      disk_space: no
      network_ports: no
      last_logins: no
      open_files: no
      process_list: no

    # Filter journald to only include critical and error messages
    journald_filters:
      - name: critical_errors
        enabled: yes
        facility: "PRIORITY" # Emergency, Alert, Critical only
        query: "[0-3]" # Emergency, Alert, Critical only

      - name: sshd
        enabled: yes
        facility: "_SYSTEMD_UNIT"
        query: "^ssh.service$"

      - name: login authentication
        enabled: yes
        facility: "_SYSTEMD_UNIT"
        query: "^system-logind.service$"

      - name: sudo authentication
        enabled: yes
        facility: "SYSLOG_IDENTIFIER"
        query: "sudo|su"

    custom: [] # Define custom logs as needed

# .............................................................................................
# Profile: internet_facing
# For internet-connected systems where Wazuh is the primary security tool and log collector
# .............................................................................................

internet_facing_profile:
  wazuh_security_modules:
    rootcheck:
      enabled: yes
      frequency: 7200 # Every 2 hours - very frequent
    syscheck:
      enabled: yes
      frequency: 7200 # Every 2 hours - very frequent
    sca:
      enabled: yes
      interval: "3h" # Very frequent assessment
    syscollector:
      enabled: yes
      interval: "30m" # More frequent inventory collection
    cis_cat:
      enabled: yes # Enable compliance scanning
      interval: "1d" # Daily scanning
    osquery:
      enabled: yes # Enable advanced endpoint visibility
    active_response:
      enabled: no # Disable automatic responses
      block_malicious: yes # Block malicious activity

  wazuh_log_monitoring:
    system:
      journald: yes # Full journald monitoring
      audit: yes # Complete audit trail
      dpkg: yes # Track all package changes
      rpm: yes # Track all package changes

    commands:
      # All system commands plus additional security checks
      disk_space: yes
      network_ports: yes
      last_logins: yes
      open_files: yes
      process_list: yes

    # Comprehensive journald monitoring with service-specific filters
    journald_filters:
      - name: all_errors
        enabled: yes
        query: "PRIORITY<=4" # Emergency through Error

      - name: web_all
        enabled: yes
        query: "UNIT=apache2.service OR UNIT=httpd.service OR UNIT=nginx.service"

      - name: ssh_all
        enabled: yes
        query: "UNIT=sshd.service"

      - name: authentication
        enabled: yes
        query: "SYSLOG_IDENTIFIER=sudo OR SYSLOG_IDENTIFIER=su"

      # added by Claude in next round
      - name: kernel_security
        enabled: yes
        facility: "SYSLOG_IDENTIFIER"
        query: "kernel|apparmor|selinux"

      - name: network_security
        enabled: yes
        facility: "_SYSTEMD_UNIT"
        # query: "NetworkManager.service|systemd-networkd.service|systemd-resolved.service"
        # query: "systemd-networkd.service|systemd-resolved.service"
        query: "systemd-networkd|networkd|dhclient|dhcpcd"

      - name: authorization
        enabled: yes
        facility: "SYSLOG_IDENTIFIER"
        query: "polkit|pam|systemd-logind"

      - name: access_control
        enabled: yes
        facility: "_SYSTEMD_UNIT"
        query: "auditd.service"

    # Define custom application logs based on deployment
    custom:
      - path: /var/log/auth.log
        format: syslog
        enabled: yes

      - path: /var/log/secure
        format: syslog
        enabled: yes

# .............................................................................................
# Profile: internet_facing
# For internet-connected systems where Wazuh is the primary security tool and log collector
# .............................................................................................

ispconfig_profile:
  wazuh_security_modules:
    rootcheck:
      enabled: yes
      frequency: 7200 # Every 2 hours - very frequent
    syscheck:
      enabled: yes
      frequency: 7200 # Every 2 hours - very frequent
    sca:
      enabled: yes
      interval: "3h" # Very frequent assessment
    syscollector:
      enabled: yes
      interval: "30m" # More frequent inventory collection
    cis_cat:
      enabled: yes # Enable compliance scanning
      interval: "1d" # Daily scanning
    osquery:
      enabled: yes # Enable advanced endpoint visibility
    active_response:
      enabled: no # Desable automatic responses
      block_malicious: yes # Block malicious activity

  wazuh_log_monitoring:
    system:
      journald: yes # Full journald monitoring
      audit: yes # Complete audit trail
      dpkg: yes # Track all package changes
      rpm: yes # Track all package changes

    local_files:
      mail: yes

    commands:
      # Disable for now.  Use Telegraf?
      disk_space: no
      network_ports: no
      last_logins: no
      open_files: no
      process_list: no

    # Comprehensive journald monitoring with service-specific filters
    journald_filters:
      - name: critical_errors
        enabled: yes
        facility: "PRIORITY"
        query: "[0-4]" # Emergency, Alert, Critical, Error only

      - name: sshd
        enabled: yes
        facility: "_SYSTEMD_UNIT"
        query: "^ssh.service$"

      - name: ispconfig web, dns, database, and email services
        enabled: yes
        facility: "_SYSTEMD_UNIT"
        query: "^postfix.service$|^dovecot.service$|^named.service$|^apache2.service$|^nginx.service$|^mariadb.service$"

      - name: login authentication
        enabled: yes
        facility: "_SYSTEMD_UNIT"
        query: "^system-logind.service$|^alloy.service$|^telegraf.service$|"

      - name: sudo authentication
        enabled: yes
        facility: "SYSLOG_IDENTIFIER"
        query: "sudo|su|kernel"

      - name: wireguard
        enabled: yes
        facility: "_SYSTEMD_UNIT"
        query: "^wg-quick@wg0.service$"

      - name: wireguard2
        enabled: yes
        facility: "MESSAGE"
        query: "(?!.*wireguard.*(?:Keypair|keepalive|handshake|packet))"

    # Define custom application logs based on deployment
    custom:
      - path: /var/log/auth.log
        format: syslog
        enabled: yes

      - path: /var/log/secure
        format: syslog
        enabled: yes

      # Now we do the ISP web stuff
      - path: /var/log/apache2/error.log
        format: apache
        enabled: yes

      - path: /var/log/ispconfig/httpd/*/error.log
        format: apache
        enabled: yes

      - path: /var/log/apache2/access.log
        format: apache
        ignore_type_pcre2: "GET /server-status\\?auto HTTP/1\\.1"
        enabled: yes

      - path: /var/log/apache2/other_vhosts_access.log
        format: apache
        enabled: yes

      - path: /var/log/ispconfig/httpd/*/access.log
        format: apache
        ignore_type_pcre2: "/var/log/ispconfig/httpd/*/access.log"
        enabled: yes

      - path: /var/log/ispconfig/httpd/*/error.log
        format: apache
        enabled: yes
##############################
