---
#  This is a pure testing system.  No DNS, no external connections
#  Tried LXC...access issues.
#  Come back to this...fix the ip address and start hardening.

- name: "Configure Monitor4"
  hosts: monitor4

  vars:
    influxdb_reload: true
    influxdb_configure: true
    loki_force_reload: false
    loki_local_storage: true

  pre_tasks:
    - name: Debug variable paths
      ansible.builtin.debug:
        msg:
          - "Playbook dir: {{ playbook_dir }}"
          - "Inventory dir: {{ inventory_dir }}"
          - "project_root: {{ inventory_dir }}"
          - "ansible_config_file: {{ ansible_config_file }}"

    - name: Install required packages
      become: true
      ansible.builtin.dnf:
        name: lsof
        state: present

    - name: Ensure ansible temp directory exists with proper permissions
      become: true
      ansible.builtin.file:
        path: /tmp/ansible-tmp
        state: directory
        owner: root
        group: root
        mode: "0777"

    - name: Print all available variables
      ansible.builtin.debug:
        msg: "{{ vars | to_nice_yaml }}"

    - name: Try accessing the specific variable
      ansible.builtin.debug:
        var: telgraf2influxdb_configs

  roles:
    - jackaltx.monitoring.influxdb
    - jackaltx.monitoring.telegraf
