---
name: Super-Linter

on:
  push:
    branches: 
      - dev
  pull_request:
    branches: 
      - dev

jobs:
  super-lint:
    name: Lint Code Base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Run Super-Linter
        uses: github/super-linter@v4
        env:
          DEFAULT_BRANCH: dev
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_ALL_CODEBASE: true
          # Enable only specific linters
          VALIDATE_YAML: true
          VALIDATE_ANSIBLE: true
          # Optional but recommended for Ansible
          VALIDATE_JSON: true
          # Disable all other linters
